#!/usr/bin/env bash
# Script to configure an Ubuntu machine with an Nginx server
# Configure the Nginx server so that /redirect_me redirects to another page permanently

sudo apt-get -y update
sudo apt-get -y install nginx

sudo sed -i '/listen \[\:\:\]\:80 default_server/ a \\n\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo sed -i '/rewrite/ a \\n\treturn 301;' /etc/nginx/sites-enabled/default
sudo service nginx restart
