#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Script to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_page.html
sudo sed -i '/listen \[\:\:\]\:80 default_server/ a \\n\terror_page 404 /error_page.html;' /etc/nginx/sites-enabled/default
sudo sed -i '/# pass PHP scripts to FastCGI server/ i \\tlocation = /error_page.html {\n\t\troot /usr/share/nginx/html;\n\t}\n' /etc/nginx/sites-enabled/default
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"
echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
