#!/usr/bin/env bash
#Displays a list of currently running processes.
#   Must show all processes, for all users, including those which might not have a TTY
#   Displays in a user-oriented format
#   Shows process hierarchy
# shellcheck disable=SC2009
ps -auxf | grep bash
